services:
  grpc-server:
    image: ghcr.io/apoorva64/eternity2/api:latest
    ports:
      - "50051:50051"
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - REDIS_URL=tcp://redis:6379

  envoy:
    build:
      context: envoy
    ports:
      - '50052:50052'


  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: secret
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data

volumes:
  redis-insight: