services:
  grpc-server:
    image: ghcr.io/apoorva64/eternity2/api:latest
    ports:
      - "50051:50051"
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file: .env

  envoy:
    image: ghcr.io/apoorva64/eternity2/envoy:latest
    build:
      context: envoy
    ports:
      - '50052:50052'

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "50053:6379"
    volumes:
      - redis-data:/data
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "50054:5540"
    volumes:
      - redis-insight:/data

volumes:
  redis-insight:
  redis-data: