services:
  grpc-server:
    image: ghcr.io/apoorva64/eternity2/api:hint
    ports:
      - "50051:50051"
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file: .env
    restart: always

  envoy:
    image: ghcr.io/apoorva64/eternity2/envoy:latest
    build:
      context: envoy
    ports:
      - '50052:50052'
    restart: always